# Generated by Django 2.2.1 on 2019-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='合成文字')),
                ('content', models.BinaryField(verbose_name='合成语音内容')),
            ],
            options={
                'db_table': 'novel_audio',
            },
        ),
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='小说名')),
                ('home', models.CharField(max_length=64, verbose_name='小说首页')),
            ],
            options={
                'db_table': 'novel_info',
            },
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.IntegerField(verbose_name='章节序号')),
                ('title', models.CharField(max_length=128, verbose_name='章节名称')),
                ('url', models.CharField(max_length=64, verbose_name='章节地址')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('flag', models.BooleanField(default=False, verbose_name='是否已经合成')),
                ('novel_info', models.ForeignKey(on_delete=False, to='fiction.NovelInfo')),
            ],
            options={
                'db_table': 'novel_chapter',
            },
        ),
    ]
